pipeline { 
    agent any 
    environment { 
        INSTAGRAM_NERIO = '@Nerio' 
    }
    options {
        skipDefaultCheckout(true)
    }

    stages {
        stage('check env') {
            steps {
                sh "mvn -v"
            }
        }
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
    } 
} 